version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: custom_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./images:/etc/nginx/images:ro
    ports:
      - "80:80"
    restart: always
